sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t dev/client -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dev/client npm run test -- --coverage