sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t dev/client -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dev/client npm run test -- --coverage

after_success:
    # Build docker images
    - docker build -t bokaderohit98/multi-container-client ./client
    - docker build -t bokaderohit98/multi-container-server ./server
    - docker build -t bokaderohit98/multi-container-worker ./worker
    - docker build -t bokaderohit98/multi-container-nginx ./nginx
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to dockerhub
    - docker push bokaderohit98/multi-container-client
    - docker push bokaderohit98/multi-container-server
    - docker push bokaderohit98/multi-container-worker
    - docker push bokaderohit98/multi-container-nginx

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-495717134924"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY